require('dotenv').config();
const { pool } = require('./db');
const bcrypt = require('bcryptjs');

async function initDB() {
  try {
    console.log('Adding permissions column to roles table if it does not exist...');
    await pool.query(`
      ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS permissions JSONB;
    `);

    console.log('Creating admin_users table...');
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.admin_users (
          id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          role_id INTEGER NOT NULL,
          full_name VARCHAR(150) NOT NULL,
          username VARCHAR(50) UNIQUE NOT NULL,
          email VARCHAR(150) UNIQUE,
          phone VARCHAR(20),
          password_hash VARCHAR(255) NOT NULL,
          is_active BOOLEAN NOT NULL DEFAULT true,
          last_login_at TIMESTAMP,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          CONSTRAINT admin_users_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles (id)
      );
    `);

    // Update roles
    console.log('Updating default roles with permissions...');
    const adminPerms = JSON.stringify({ allowedMenus: ['all'] });
    const managerPerms = JSON.stringify({ allowedMenus: ['/', '/invoices', '/master-customer'] });
    const frontDeskPerms = JSON.stringify({ allowedMenus: ['/', '/invoices'] });
    
    await pool.query(`UPDATE public.roles SET permissions = $1::jsonb WHERE id = 1;`, [adminPerms]);
    await pool.query(`UPDATE public.roles SET permissions = $1::jsonb WHERE id = 2;`, [managerPerms]);
    await pool.query(`UPDATE public.roles SET permissions = $1::jsonb WHERE id = 3;`, [frontDeskPerms]);

    // Insert default admin
    console.log('Inserting default admin user...');
    const hash = await bcrypt.hash('password123', 10);
    await pool.query(`
      INSERT INTO public.admin_users (role_id, full_name, username, email, password_hash)
      VALUES (1, 'Main Administrator', 'admin', 'admin@example.com', $1)
      ON CONFLICT (username) DO NOTHING;
    `, [hash]);

    console.log('Database initialization complete!');
  } catch (err) {
    console.error('Error initializing database:', err);
  } finally {
    await pool.end();
  }
}

initDB();
